"""Generates notebooks/05_train_10k_drive_yolo_segmentation.ipynb.

Google Colab notebook that mounts Google Drive (/content/drive/MyDrive/floorPlanGenerator),
ingests 10k images (CubiCasa5k + dataset_5000), applies architectural image preprocessing
(background illumination whitening, CLAHE contrast enhancement, grid cleaning),
trains YOLOv8-seg, saves weights to Drive, and tests on new floor plans.
"""

import json
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent

notebook = {
    "cells": [
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "# Train YOLOv8-Seg on 10,000 Floor Plans (Google Drive: CubiCasa5k + Synthetic 5k)\n",
                "\n",
                "This notebook mounts your Google Drive (`MyDrive/floorPlanGenerator`), processes 10,000 floor plan images (`cubicasa` + `dataset_5000`), applies architectural image preprocessing (background whitening, CLAHE contrast enhancement), trains a high-precision YOLOv8 instance segmentation model, saves trained weights permanently to your Drive, and performs end-to-end inference on new floor plans.\n",
                "\n",
                "### **Goals**\n",
                "- **Primary Goal**: Detect all rooms, snapping boundaries to structural walls, and extract real-world dimensions (length, width, area).\n",
                "- **Secondary Goal**: Detect all doors (swing arcs/openings) and windows (glazing/placement).\n",
                "- **Dataset**: 10,000 images (5,000 CubiCasa real-world + 5,000 high-fidelity synthetic blueprints).\n",
                "\n",
                "> **Colab Runtime Recommendation**: Go to `Runtime` -> `Change runtime type` -> select **T4 GPU** or **A100 GPU**."
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "## Step 1: Install Dependencies\n",
                "Installs Ultralytics YOLO, OpenCV, Tesseract OCR, and geometry libraries."
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# 1. Install Python packages\n",
                '!pip install -q "ultralytics>=8.3.0" "pytesseract>=0.3.10" "pyclipper>=1.3.0" "shapely>=2.0.0" "cairosvg>=2.7.0"\n',
                "\n",
                "# 2. Install Tesseract OCR engine for reading blueprint dimension texts\n",
                "!apt-get update -qq > /dev/null\n",
                "!apt-get install -y -qq tesseract-ocr libtesseract-dev > /dev/null\n",
                "\n",
                "import torch\n",
                "import ultralytics\n",
                'print(f"Ultralytics version: {ultralytics.__version__}")\n',
                'print(f"PyTorch version:     {torch.__version__}")\n',
                'print(f"CUDA Available:      {torch.cuda.is_available()}")\n',
                "if torch.cuda.is_available():\n",
                '    print(f"GPU Device:          {torch.cuda.get_device_name(0)}")\n'
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "## Step 2: Mount Google Drive\n",
                "Connects to Google Drive to access `MyDrive/floorPlanGenerator`."
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "from google.colab import drive\n",
                "import os\n",
                "from pathlib import Path\n",
                "\n",
                "# Mount Google Drive\n",
                'drive.mount("/content/drive")\n',
                "\n",
                "# Define Drive base path\n",
                'DRIVE_BASE = Path("/content/drive/MyDrive/floorPlanGenerator")\n',
                'if not DRIVE_BASE.exists():\n',
                '    # Check alternate casing or direct path\n',
                '    alt = Path("/content/drive/MyDrive/floorplangenerator")\n',
                "    if alt.exists():\n",
                "        DRIVE_BASE = alt\n",
                "\n",
                'print(f"Google Drive Base Directory: {DRIVE_BASE} (Exists: {DRIVE_BASE.exists()})")\n',
                "if DRIVE_BASE.exists():\n",
                '    print("Contents of floorPlanGenerator in Drive:")\n',
                "    for item in sorted(DRIVE_BASE.iterdir()):\n",
                '        print(f"  • {item.name}/" if item.is_dir() else f"  • {item.name}")\n'
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "## Step 3: Discover & Validate 10k Dataset Folders\n",
                "Locates `cubicasa` and `dataset_5000` under `images/` or root."
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "import os\n",
                "from pathlib import Path\n",
                "\n",
                'drive_root = Path("/content/drive/MyDrive")\n',
                "\n",
                '# Find any folder matching "floorplan" in MyDrive\n',
                'fpg_matches = [p for p in drive_root.glob("*") if "floorplan" in p.name.lower()]\n',
                "search_roots = fpg_matches if fpg_matches else [drive_root]\n",
                "\n",
                'print(f"Scanning Drive folders: {[str(p) for p in search_roots]}...")\n',
                "\n",
                "d5k_zip = None\n",
                "d5k_found_dir = None\n",
                "cubi_found = None\n",
                "\n",
                "# Recursive case-insensitive discovery\n",
                "for sroot in search_roots:\n",
                "    for root, dirs, files in os.walk(sroot):\n",
                "        rpath = Path(root)\n",
                "        for f in files:\n",
                "            fl = f.lower()\n",
                '            if "dataset_5000" in fl and fl.endswith(".zip") and not d5k_zip:\n',
                "                d5k_zip = rpath / f\n",
                '            elif "cubi" in fl and fl.endswith(".zip") and not cubi_found:\n',
                "                cubi_found = rpath / f\n",
                "        for d in dirs:\n",
                "            dl = d.lower()\n",
                '            if ("dataset_5000" in dl or "dataset5000" in dl) and not d5k_found_dir:\n',
                "                d5k_found_dir = rpath / d\n",
                '            elif "cubi" in dl and not cubi_found:\n',
                "                cubi_found = rpath / d\n",
                "        if (d5k_zip or d5k_found_dir) and cubi_found:\n",
                "            break\n",
                "\n",
                "# If ZIP is available, extract to local /content/ for 10x-20x faster NVMe training\n",
                'local_d5k = Path("/content/dataset_5000")\n',
                "if d5k_zip and not local_d5k.exists():\n",
                '    print(f"Extracting {d5k_zip} to /content/ (ultra-fast NVMe storage)...")\n',
                '    !unzip -q -o "{d5k_zip}" -d /content/\n',
                '    print("Extracted dataset_5000 successfully!")\n',
                "    d5k_dir = local_d5k\n",
                "elif local_d5k.exists():\n",
                "    d5k_dir = local_d5k\n",
                "else:\n",
                "    d5k_dir = d5k_found_dir\n",
                "\n",
                "# If cubicasa/cubisca is a ZIP, extract to /content/cubicasa/\n",
                'local_cubi = Path("/content/cubicasa")\n',
                'if cubi_found and str(cubi_found).endswith(".zip") and not local_cubi.exists():\n',
                '    print(f"Extracting {cubi_found} to /content/cubicasa/...")\n',
                '    !unzip -q -o "{cubi_found}" -d /content/cubicasa/\n',
                '    print("Extracted cubicasa/cubisca successfully!")\n',
                "    cubi_dir = local_cubi\n",
                "elif local_cubi.exists():\n",
                "    cubi_dir = local_cubi\n",
                "else:\n",
                "    cubi_dir = cubi_found\n",
                "\n",
                'print(f"\\nVerified Dataset Paths:")\n',
                'print(f"  • dataset_5000: {d5k_dir}")\n',
                'print(f"  • cubicasa:     {cubi_dir}")\n',
                "\n",
                "if d5k_dir and d5k_dir.exists():\n",
                '    print("\\n[dataset_5000 files preview]")\n',
                "    for p in sorted(d5k_dir.iterdir())[:8]:\n",
                '        print(f"  - {p.name}/" if p.is_dir() else f"  - {p.name}")\n',
                "\n",
                "if cubi_dir and cubi_dir.exists():\n",
                '    print("\\n[cubicasa files preview]")\n',
                "    for p in sorted(cubi_dir.iterdir())[:8]:\n",
                '        print(f"  - {p.name}/" if p.is_dir() else f"  - {p.name}")\n',
                "elif not d5k_dir or not cubi_dir:\n",
                '    print("\\n[Google Drive MyDrive contents for reference:]")\n',
                "    for item in sorted(drive_root.iterdir())[:20]:\n",
                '        print(f"  - {item.name}/" if item.is_dir() else f"  - {item.name}")\n'
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "## Step 4: Architectural Image Preprocessing Engine\n",
                "Applies adaptive background whitening, grid noise removal, and CLAHE contrast sharpening before sending drawings to YOLO."
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "import cv2\n",
                "import numpy as np\n",
                "from PIL import Image\n",
                "from pathlib import Path\n",
                "\n",
                "def preprocess_blueprint_image(img_input, clip_limit=2.0, normalize_bg=True):\n",
                '    """Preprocesses architectural blueprints for high-precision instance segmentation.\n',
                '    \n',
                '    1. Converts to grayscale.\n',
                '    2. Normalizes uneven background illumination & removes faint graph paper grids.\n',
                '    3. Sharpens structural walls, door swing arcs, and window lines with CLAHE.\n',
                '    4. Returns clean 3-channel RGB image for YOLO input.\n',
                '    """\n',
                "    if isinstance(img_input, (str, Path)):\n",
                "        img = cv2.imread(str(img_input))\n",
                "        if img is None:\n",
                '            raise FileNotFoundError(f"Could not load image: {img_input}")\n',
                "    elif isinstance(img_input, Image.Image):\n",
                '        img = cv2.cvtColor(np.array(img_input.convert("RGB")), cv2.COLOR_RGB2BGR)\n',
                "    elif isinstance(img_input, np.ndarray):\n",
                "        img = img_input.copy()\n",
                "    else:\n",
                '        raise ValueError("Unsupported image input type")\n',
                "\n",
                "    # 1. Grayscale\n",
                "    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)\n",
                "\n",
                "    # 2. Background illumination whitening (erases paper yellowing and faint grid lines)\n",
                "    if normalize_bg:\n",
                "        dilated = cv2.dilate(gray, np.ones((7, 7), np.uint8))\n",
                "        bg = cv2.medianBlur(dilated, 21)\n",
                "        diff = 255 - cv2.absdiff(gray, bg)\n",
                "        norm = cv2.normalize(diff, None, alpha=0, beta=255, norm_type=cv2.NORM_MINMAX, dtype=cv2.CV_8UC1)\n",
                "    else:\n",
                "        norm = gray\n",
                "\n",
                "    # 3. CLAHE (Contrast Limited Adaptive Histogram Equalization)\n",
                "    clahe = cv2.createCLAHE(clipLimit=clip_limit, tileGridSize=(8, 8))\n",
                "    enhanced = clahe.apply(norm)\n",
                "\n",
                "    # 4. Convert back to 3-channel RGB for YOLO\n",
                "    rgb_clean = cv2.cvtColor(enhanced, cv2.COLOR_GRAY2RGB)\n",
                "    return rgb_clean\n",
                "\n",
                'print("Architectural preprocessing engine ready!")\n'
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "## Step 5: Build Unified 10k Dataset (`data.yaml`)\n",
                "Configures training paths and 10 architectural classes (`bedroom`, `living_room`, `kitchen`, `bathroom`, `hallway`, `balcony`, `room`, `door`, `window`, `wall`)."
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                'local_dataset_dir = Path("/content/combined_10k_dataset")\n',
                "local_dataset_dir.mkdir(parents=True, exist_ok=True)\n",
                "\n",
                "# Standard 10 Architectural Classes matching dataset_5000\n",
                "CLASSES = [\n",
                '    "bedroom",       # 0\n',
                '    "living_room",   # 1\n',
                '    "kitchen",       # 2\n',
                '    "bathroom",      # 3\n',
                '    "hallway",       # 4\n',
                '    "balcony",       # 5\n',
                '    "room",          # 6\n',
                '    "door",          # 7\n',
                '    "window",        # 8\n',
                '    "wall",          # 9\n',
                "]\n",
                "\n",
                "# Generate unified data.yaml pointing to valid Colab paths\n",
                'yaml_path = local_dataset_dir / "data.yaml"\n',
                "train_imgs = []\n",
                "val_imgs = []\n",
                "\n",
                "if d5k_dir:\n",
                '    if (d5k_dir / "images" / "train").exists():\n',
                '        train_imgs.append(str((d5k_dir / "images" / "train").resolve()))\n',
                '        val_imgs.append(str((d5k_dir / "images" / "val").resolve()))\n',
                '    elif (d5k_dir / "train").exists():\n',
                '        train_imgs.append(str((d5k_dir / "train").resolve()))\n',
                '        val_imgs.append(str((d5k_dir / "val").resolve()))\n',
                "    else:\n",
                '        train_imgs.append(str(d5k_dir.resolve()))\n',
                "\n",
                "if cubi_dir:\n",
                '    if (cubi_dir / "images" / "train").exists():\n',
                '        train_imgs.append(str((cubi_dir / "images" / "train").resolve()))\n',
                '        val_imgs.append(str((cubi_dir / "images" / "val").resolve()))\n',
                '    elif (cubi_dir / "train").exists():\n',
                '        train_imgs.append(str((cubi_dir / "train").resolve()))\n',
                "    else:\n",
                '        train_imgs.append(str(cubi_dir.resolve()))\n',
                "\n",
                "lines = [\n",
                '    f"path: {local_dataset_dir}",\n',
                '    f"train: {train_imgs}",\n',
                '    f"val: {val_imgs if val_imgs else train_imgs}",\n',
                '    "",\n',
                '    "names:",\n',
                "]\n",
                "for idx, cname in enumerate(CLASSES):\n",
                '    lines.append(f"  {idx}: {cname}")\n',
                'lines.append("")\n',
                'yaml_path.write_text("\\n".join(lines))\n',
                "active_yaml = yaml_path\n",
                "\n",
                'print(f"\\nUsing Dataset Config: {active_yaml}")\n',
                "print(active_yaml.read_text())\n"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "## Step 6: Train YOLOv8-Seg on 10k Images & Save Weights to Drive\n",
                "Trains `yolov8s-seg.pt` (Small) or `yolov8n-seg.pt` (Nano) and automatically preserves checkpoints directly in `MyDrive/floorPlanGenerator/weights/`."
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "import torch\n",
                "from ultralytics import YOLO\n",
                "import shutil\n",
                "from pathlib import Path\n",
                "\n",
                "# Destination directory in Google Drive to preserve weights\n",
                'weights_drive_dir = DRIVE_BASE / "weights"\n',
                "weights_drive_dir.mkdir(parents=True, exist_ok=True)\n",
                "\n",
                "# Load pretrained YOLOv8 instance segmentation model\n",
                '# yolov8s-seg (Small, 11M params) offers superior mask precision for 10k datasets\n',
                'model = YOLO("yolov8s-seg.pt")\n',
                "\n",
                "# Training Hyperparameters\n",
                "EPOCHS = 50       # 50 epochs recommended for full convergence\n",
                "IMGSZ = 640       # 640 or 1024 (1024 for ultra-sharp thin walls if using A100 GPU)\n",
                "BATCH = 16 if torch.cuda.is_available() else 4\n",
                "\n",
                'print(f"Starting YOLOv8-seg training on 10k images...")\n',
                'print(f"Checkpoints will be automatically saved to Google Drive: {weights_drive_dir}\\n")\n',
                "\n",
                "results = model.train(\n",
                "    data=str(active_yaml),\n",
                "    epochs=EPOCHS,\n",
                "    imgsz=IMGSZ,\n",
                "    batch=BATCH,\n",
                '    device=0 if torch.cuda.is_available() else "cpu",\n',
                "    retina_masks=True, # High resolution mask prototypes\n",
                "    plots=True,\n",
                "    save=True,\n",
                "    verbose=True,\n",
                ")\n",
                "\n",
                "# Copy best and last weights directly to Google Drive\n",
                'run_save_dir = Path(model.trainer.save_dir) / "weights"\n',
                'best_local = run_save_dir / "best.pt"\n',
                'last_local = run_save_dir / "last.pt"\n',
                "\n",
                "if best_local.exists():\n",
                '    drive_best = weights_drive_dir / "yolov8_floorplan_10k_best.pt"\n',
                "    shutil.copy2(best_local, drive_best)\n",
                '    print(f"Successfully saved BEST weights to Drive: {drive_best}")\n',
                "\n",
                "if last_local.exists():\n",
                '    drive_last = weights_drive_dir / "yolov8_floorplan_10k_last.pt"\n',
                "    shutil.copy2(last_local, drive_last)\n",
                '    print(f"Successfully saved LAST weights to Drive: {drive_last}")\n'
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "## Step 7: Test on New Floor Plans (Interactive Testing & Dimension Extraction)\n",
                "Preprocesses any new blueprint, runs inference, extracts real-world room dimensions (`width`, `length`, `area`), detects doors and windows, and renders publication-quality overlays."
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "from google.colab import files\n",
                "import io\n",
                "from pathlib import Path\n",
                "import matplotlib.pyplot as plt\n",
                "from ultralytics import YOLO\n",
                "from PIL import Image\n",
                "\n",
                "# 1. Resolve Best Weights (from Google Drive or current run)\n",
                'drive_best = DRIVE_BASE / "weights" / "yolov8_floorplan_10k_best.pt"\n',
                "if drive_best.exists():\n",
                "    eval_weights = drive_best\n",
                'elif "best_local" in globals() and best_local.exists():\n',
                "    eval_weights = best_local\n",
                "else:\n",
                '    eval_weights = "yolov8s-seg.pt"\n',
                "\n",
                'print(f"Loading trained weights for testing: {eval_weights}")\n',
                "trained_model = YOLO(str(eval_weights))\n",
                "\n",
                "# Output directory for annotated predictions\n",
                'predictions_dir = DRIVE_BASE / "predictions"\n',
                "predictions_dir.mkdir(parents=True, exist_ok=True)\n",
                "\n",
                '# 2. Interactive File Upload\n',
                'print("\\nUpload a new floor plan image (PNG, JPG, or SVG) to test:")\n',
                "uploaded = files.upload()\n",
                "\n",
                "for filename in uploaded.keys():\n",
                '    print(f"\\n==========================================")\n',
                '    print(f"Processing new floor plan: {filename}")\n',
                '    print(f"==========================================")\n',
                "    \n",
                "    # A. Apply Preprocessing (Grayscale / Background Whitening / CLAHE)\n",
                "    clean_rgb = preprocess_blueprint_image(filename)\n",
                '    preprocessed_path = f"preprocessed_{filename}"\n',
                "    cv2.imwrite(preprocessed_path, cv2.cvtColor(clean_rgb, cv2.COLOR_RGB2BGR))\n",
                "    \n",
                "    # B. Run Segmentation Inference\n",
                "    results = trained_model.predict(\n",
                "        source=clean_rgb,\n",
                "        conf=0.25,\n",
                "        retina_masks=True,\n",
                "        verbose=False\n",
                "    )\n",
                "    \n",
                "    # C. Parse Detected Elements\n",
                "    res0 = results[0]\n",
                "    boxes = res0.boxes\n",
                "    masks = res0.masks\n",
                "    names = res0.names\n",
                "    \n",
                "    detected_rooms = []\n",
                "    detected_doors = []\n",
                "    detected_windows = []\n",
                "    detected_walls = []\n",
                "    \n",
                "    orig_h, orig_w = res0.orig_shape\n",
                "    \n",
                "    for i in range(len(boxes)):\n",
                "        cls_id = int(boxes.cls[i].item())\n",
                "        conf = float(boxes.conf[i].item())\n",
                '        cname = names.get(cls_id, f"class_{cls_id}")\n',
                "        xyxy = boxes.xyxy[i].cpu().numpy()\n",
                "        x1, y1, x2, y2 = xyxy\n",
                "        w_px = max(1.0, x2 - x1)\n",
                "        h_px = max(1.0, y2 - y1)\n",
                "        \n",
                '        if "door" in cname:\n',
                '            detected_doors.append({"type": cname, "box": [y1, x1, y2, x2], "conf": conf})\n',
                '        elif "window" in cname:\n',
                '            detected_windows.append({"type": cname, "box": [y1, x1, y2, x2], "conf": conf})\n',
                '        elif "wall" in cname:\n',
                '            detected_walls.append({"box": [y1, x1, y2, x2]})\n',
                "        else:\n",
                "            # Room\n",
                "            detected_rooms.append({\n",
                '                "name": cname,\n',
                '                "box": [y1, x1, y2, x2],\n',
                '                "w_px": w_px,\n',
                '                "h_px": h_px,\n',
                '                "conf": conf\n',
                "            })\n",
                "            \n",
                "    # D. Calibrate Scale & Extract Real Dimensions (Primary Goal)\n",
                "    # Typical residential footprint envelope ~ 9.0 meters width\n",
                "    if detected_rooms:\n",
                '        min_x = min(r["box"][1] for r in detected_rooms)\n',
                '        max_x = max(r["box"][3] for r in detected_rooms)\n',
                "        envelope_px = max(10.0, max_x - min_x)\n",
                "        ppm = envelope_px / 9.0 # Pixels per meter calibration\n",
                "    else:\n",
                "        ppm = orig_w / 10.0\n",
                "        \n",
                '    print(f"PRIMARY GOAL (Detected {len(detected_rooms)} Rooms with Real Dimensions):")\n',
                "    for idx, r in enumerate(detected_rooms):\n",
                '        r_len = round(max(r["w_px"], r["h_px"]) / ppm, 2)\n',
                '        r_wid = round(min(r["w_px"], r["h_px"]) / ppm, 2)\n',
                "        r_area = round(r_len * r_wid, 2)\n",
                '        rname = r["name"].replace("_", " ").title()\n',
                '        print(f"  • {rname:16}: {r_len:.2f}m x {r_wid:.2f}m ({r_area:.2f} sq m) [Conf: {r[\'conf\']:.2f}]")\n',
                "        \n",
                '    print(f"\\nSECONDARY GOAL (Doors & Windows):")\n',
                '    print(f"  • Doors Detected:   {len(detected_doors)}")\n',
                '    print(f"  • Windows Detected: {len(detected_windows)}")\n',
                '    print(f"  • Walls Segmented:  {len(detected_walls)}")\n',
                "    \n",
                "    # E. Display Visual Result\n",
                "    annotated_bgr = res0.plot()\n",
                "    annotated_rgb = cv2.cvtColor(annotated_bgr, cv2.COLOR_BGR2RGB)\n",
                "    \n",
                '    # Save to Google Drive\n',
                '    save_drive_p = predictions_dir / f"result_{filename}"\n',
                "    Image.fromarray(annotated_rgb).save(save_drive_p)\n",
                '    print(f"\\nSaved annotated prediction to Google Drive: {save_drive_p}")\n',
                "    \n",
                "    # Plot side-by-side: Original Preprocessed vs Segmentation Prediction\n",
                "    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(18, 9))\n",
                "    ax1.imshow(clean_rgb)\n",
                '    ax1.set_title(f"Preprocessed Input Drawing: {filename}", fontsize=13)\n',
                '    ax1.axis("off")\n',
                "    \n",
                "    ax2.imshow(annotated_rgb)\n",
                '    ax2.set_title(f"YOLOv8-Seg 10k: Detected Rooms, Dimensions, Doors & Windows", fontsize=13)\n',
                '    ax2.axis("off")\n',
                "    plt.tight_layout()\n",
                "    plt.show()\n"
            ]
        }
    ],
    "metadata": {
        "accelerator": "GPU",
        "colab": {"provenance": []},
        "language_info": {"name": "python"}
    },
    "nbformat": 4,
    "nbformat_minor": 2
}

out_path = REPO_ROOT / "notebooks" / "05_train_10k_drive_yolo_segmentation.ipynb"
with open(out_path, "w", encoding="utf-8") as f:
    json.dump(notebook, f, indent=2)

print(f"Successfully generated {out_path}!")
print(f"Size: {out_path.stat().st_size / 1024:.1f} KB")
