"""Build Google Colab Notebook for running Frontier Reasoning LLMs on Floor Plan Prompts."""

import json
from pathlib import Path

def create_notebook():
    nb = {
        "cells": [],
        "metadata": {
            "accelerator": "GPU",
            "colab": {
                "gpuType": "T4",
                "provenance": []
            },
            "kernelspec": {
                "display_name": "Python 3",
                "name": "python3"
            },
            "language_info": {
                "name": "python"
            }
        },
        "nbformat": 4,
        "nbformat_minor": 0
    }

    def add_md(text):
        nb["cells"].append({
            "cell_type": "markdown",
            "metadata": {},
            "source": [line + "\n" for line in text.strip().split("\n")]
        })

    def add_code(code):
        nb["cells"].append({
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [line + "\n" for line in code.strip().split("\n")]
        })

    # Cell 1: Intro
    add_md(
        "# 📐 Floor Plan CAD Refiner via Reasoning LLMs (Google Colab T4/L4/A100)\n\n"
        "This notebook takes the multi-sensor intermediate representation generated by your local pipeline:\n"
        "- **YOLOv8-seg**: Semantic bounding boxes (rooms, doors, windows)\n"
        "- **OpenCV LSD**: Sub-pixel wall vectors & orthogonal grid axes\n"
        "- **Tesseract OCR**: Ground-truth dimensions ('14.50m total', '5.00m x 4.00m')\n\n"
        "And feeds it into an advanced **Frontier Reasoning LLM** (`DeepSeek-R1-Distill-Qwen-8B` or `Qwen2.5-Coder-7B`) "
        "running directly inside Colab in 4-bit precision to generate clean, production-ready vector CAD / SVG code."
    )

    # Cell 2: Install dependencies
    add_code(
        "# 🚀 Step 1: Install Dependencies\n"
        "!pip install -q transformers bitsandbytes accelerate\n"
        "print('✅ Libraries installed successfully!')"
    )

    # Cell 3: GPU Check
    add_code(
        "# 🔍 Step 2: Verify GPU Acceleration\n"
        "import torch\n"
        "print('CUDA Available:', torch.cuda.is_available())\n"
        "if torch.cuda.is_available():\n"
        "    print('Active GPU:', torch.cuda.get_device_name(0))\n"
        "    vram = torch.cuda.get_device_properties(0).total_memory / (1024**3)\n"
        "    print(f'Total VRAM: {vram:.2f} GB')\n"
        "else:\n"
        "    print('⚠️ WARNING: GPU not detected! Go to Runtime -> Change runtime type -> Select T4 GPU.')"
    )

    # Cell 4: Load Model
    add_code(
        "# 🧠 Step 3: Load Reasoning Model in 4-bit NF4\n"
        "# Uses only ~5.5 GB VRAM (Fits easily on Free Colab T4 15GB GPU)\n"
        "import torch\n"
        "from transformers import AutoTokenizer, AutoModelForCausalLM, BitsAndBytesConfig\n\n"
        "# Model Selection:\n"
        "# Option 1 (Default): DeepSeek-R1-Distill-Qwen-8B (Elite chain-of-thought architectural reasoning)\n"
        "# Option 2: Qwen/Qwen2.5-Coder-7B-Instruct (Precise CAD / SVG code generation)\n"
        "model_id = 'deepseek-ai/DeepSeek-R1-Distill-Qwen-8B'\n\n"
        "print(f'⏳ Downloading & Loading {model_id} in 4-bit...')\n\n"
        "quant_config = BitsAndBytesConfig(\n"
        "    load_in_4bit=True,\n"
        "    bnb_4bit_quant_type='nf4',\n"
        "    bnb_4bit_compute_dtype=torch.float16,\n"
        ")\n\n"
        "tokenizer = AutoTokenizer.from_pretrained(model_id)\n"
        "model = AutoModelForCausalLM.from_pretrained(\n"
        "    model_id,\n"
        "    quantization_config=quant_config,\n"
        "    device_map='auto'\n"
        ")\n\n"
        "print(f'✅ Model {model_id} loaded and ready!')"
    )

    # Cell 5: Provide Prompt File
    add_code(
        "# 📄 Step 4: Load the Master Prompt\n"
        "# You can upload your 'gemini_reasoning_prompt.md' using Colab's file sidebar,\n"
        "# or run this cell to select and upload it directly.\n\n"
        "import os\n"
        "from google.colab import files\n\n"
        "prompt_path = 'gemini_reasoning_prompt.md'\n\n"
        "if not os.path.exists(prompt_path):\n"
        "    print('📁 Please upload your gemini_reasoning_prompt.md file:')\n"
        "    uploaded = files.upload()\n"
        "    for fn in uploaded.keys():\n"
        "        if fn.endswith('.md'):\n"
        "            prompt_path = fn\n"
        "            break\n\n"
        "with open(prompt_path, 'r', encoding='utf-8') as f:\n"
        "    prompt_text = f.read()\n\n"
        "print(f'✅ Loaded prompt from {prompt_path} ({len(prompt_text):,} characters)!')"
    )

    # Cell 6: Run Inference
    add_code(
        "# ⚡ Step 5: Run Architectural Reasoning & SVG Generation\n"
        "import time\n\n"
        "print('🧠 Thinking through architectural constraints & generating CAD plan...')\n"
        "start_time = time.time()\n\n"
        "messages = [{'role': 'user', 'content': prompt_text}]\n"
        "prompt_formatted = tokenizer.apply_chat_template(messages, tokenize=False, add_generation_prompt=True)\n\n"
        "inputs = tokenizer(prompt_formatted, return_tensors='pt').to('cuda')\n\n"
        "with torch.no_grad():\n"
        "    outputs = model.generate(\n"
        "        **inputs,\n"
        "        max_new_tokens=3000,\n"
        "        temperature=0.2,\n"
        "        top_p=0.95,\n"
        "        do_sample=True,\n"
        "    )\n\n"
        "output_text = tokenizer.decode(outputs[0][inputs.input_ids.shape[1]:], skip_special_tokens=True)\n"
        "elapsed = time.time() - start_time\n"
        "print(f'✨ Finished generation in {elapsed:.1f} seconds!')"
    )

    # Cell 7: Display & Save SVG
    add_code(
        "# 🎨 Step 6: Render & Save Vector Floor Plan\n"
        "import re\n"
        "from IPython.display import display, HTML\n"
        "from google.colab import files\n\n"
        "svg_match = re.search(r'(<svg[\\s\\S]*?</svg>)', output_text)\n\n"
        "if svg_match:\n"
        "    svg_code = svg_match.group(1)\n"
        "    output_filename = 'refined_cad_floorplan.svg'\n"
        "    with open(output_filename, 'w', encoding='utf-8') as f:\n"
        "        f.write(svg_code)\n"
        "    print(f'💾 Saved SVG to: {output_filename}')\n"
        "    print('👇 Rendered Vector CAD Floor Plan:')\n"
        "    display(HTML(f'<div style=\"background:#fff; padding:20px; border-radius:8px; border:1px solid #e2e8f0;\">{svg_code}</div>'))\n"
        "    \n"
        "    # Download automatically to your computer\n"
        "    files.download(output_filename)\n"
        "else:\n"
        "    print('⚠️ Could not extract <svg> tag. Printing full model response:\\n')\n"
        "    print(output_text)"
    )

    out_file = Path("notebooks/07_colab_reasoning_cad_refiner.ipynb")
    out_file.parent.mkdir(parents=True, exist_ok=True)
    with open(out_file, "w", encoding="utf-8") as f:
        json.dump(nb, f, indent=2)

    print(f"✅ Generated {out_file} with {len(nb['cells'])} cells successfully!")

if __name__ == "__main__":
    create_notebook()
